SOLVER:
  gpu: 0,
  run: train
  logdir: logs/finetune_LR_20/D9_2cm
  max_epoch: 300
  test_every_epoch: 2
  weight_decay: 0.0

  # learning rate
  lr: 0.05
  lr_type: poly
  step_size: (200,300)  # has no effect for `poly`

DATA:
  train:
    name: scannet
    semi: False          # True if Using unlabeled data for semi-training
    # octree building
    depth: 9
    node_dis: True
    offset: 0.0

    # data augmentations
    distort: True
    angle: (0, 0, 180)
    scale: 0.1
    jitter: 0.1
    uniform: True

    # data loading
    location: data/scannet/train
    filelist: data/scannet/scannetv2_train.txt
    limited_reconst: points/LR/20.txt
    batch_size: 2
    shuffle: True
    in_memory: False

  test:
    name: scannet
    top_pct: 20
    # octree building
    depth: 9
    node_dis: True
    offset: 0.0

    # data augmentations
    distort: False  # no data augmentation
    angle: (0, 0, 180)
    scale: 0.1
    jitter: 0.1
    uniform: True

    # data loading
    location: data/scannet/train
    filelist: data/scannet/scannetv2_val.txt
    batch_size: 1
    shuffle: False
    in_memory: False

MODEL:
  name: unet
  channel: 7
  nout: 21
  depth: 9
  nempty: True
  interp: nearest
  sync_bn: False
  use_checkpoint: False
  pretrain_file: 'ckpt/mp3d_00080.model.pth'
  pseudo_file: '/work/bryanyu1997/logs/finetune_LR_20/D9_2cm/checkpoints/00300.model.pth'

LOSS:
  mask: 0
  point_wise: True
  num_class: 21
  weight_sum: 0.5
  alpha: 0.999
  consistency: 10
  consist_rampup: 30
  pseudo_rate: 0.2